In [49]:
import torch
from torch import nn,Tensor
import torch.nn.functional as F
from d2l import torch as d2l

In [2]:
class CenteredLayer(nn.Module):
  def __init__(self) -> None:
    super().__init__()
  def forward(self,X:Tensor):
    return X-X.mean()

In [3]:
layer = CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [4]:
net = nn.Sequential(nn.Linear(8,128),CenteredLayer())

In [5]:
Y = net(torch.rand(4,8))
Y.mean()

tensor(5.5879e-09, grad_fn=<MeanBackward0>)

In [50]:
class MyLinear(nn.Module):
  def __init__(self,in_units,units) -> None:
    super().__init__()
    self.weight = nn.Parameter(torch.randn(in_units,units))
    self.bias = nn.Parameter(torch.randn(units,))
  def forward(self,X):
    linear = torch.matmul(X,self.weight.data) + self.bias.data
    return F.relu(linear)

In [51]:
linear = MyLinear(5,3)
linear.weight

Parameter containing:
tensor([[ 0.6363,  1.2465,  0.8886],
        [ 0.1580, -1.8252, -0.7852],
        [ 1.3040, -0.5266,  0.7908],
        [ 0.1922, -0.7424, -2.4460],
        [-0.0369,  0.6400,  0.7918]], requires_grad=True)

In [52]:
linear(torch.rand(2,5))

tensor([[1.2816, 0.2933, 0.0000],
        [0.6601, 0.4116, 0.3901]])

In [54]:
net = nn.Sequential(MyLinear(64,8),MyLinear(8,1))
net(torch.randn(2, 64))

tensor([[16.8255],
        [67.1479]])