In [13]:
import torch
from torch import nn,Tensor
import torch.nn.functional as F
from d2l import torch as d2l

In [4]:
x = torch.arange(4)
torch.save(x,'x-file')

In [6]:
x2 = torch.load('x-file')
x2

tensor([0, 1, 2, 3])

In [7]:
y = torch.zeros(4)
torch.save([x,y],'x-files')
x2,y2 = torch.load('x-files')
(x2,y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [8]:
myDict = {
  'x':x,
  'y':y
}
torch.save(myDict,'myDict')
myDict2 = torch.load('myDict')
myDict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

In [18]:
class MLP(nn.Module):
  def __init__(self) -> None:
    super().__init__()
    self.hidden = nn.Linear(20,256)
    self.output = nn.Linear(256,10)
  def forward(self,X):
    return self.output(F.relu(self.hidden(X)))
  
  
  
net = MLP()
X = torch.randn(2,20)
Y = net(X)

In [19]:
torch.save(net.state_dict(),'mlp.params')

In [20]:
clone = MLP()
clone.load_state_dict(torch.load("mlp.params"))
# 从train模式改为test模式
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [21]:
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])